### ISSUE TITLE
Package errors in Unity 2020.3.41

### ISSUE THREAD

**Issue by AlexandreFiset** [alelievr/HDRP-UI-Camera-Stacking#20]
The package doesn't compile in the latest 2020.3 LTS version of Unity, throwing the following errors:

`CameraStackingCompositing.cs(86,53): error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'UnityEngine.RenderTexture' and 'UnityEngine.Rendering.BuiltinRenderTextureType'`

and

`HDCameraUI.cs(248,146): error CS0117: 'ClearFlag' does not contain a definition for 'DepthStencil'`

Both are odds and I don't know how to fix them.
